[task.default]
build = "solvra build"
run = "solvra run"
test = "cargo test"

[task.nightly]
build = "cargo +nightly build --all"
run = "solvra run --experimental"
test = "cargo +nightly test --all"

[project]
name = "SolvraIDE"
autodetect = true
