[package]
name = "plugin_sdk"
version = "0.1.0"
edition = "2021"
rust-version = "1.78"

[dependencies]
wasmtime = { version = ">=37.0,<38.0" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
